In [1]:
import numpy as np

a = np.random.randn(5)
print(a)

[ 2.20987873  0.89157883 -1.96500936 -1.02289797  2.21218516]


In [2]:
print(a.shape)

(5,)


In [3]:
print(a.T)

[ 2.20987873  0.89157883 -1.96500936 -1.02289797  2.21218516]


In [4]:
print(np.dot(a,a.T))

15.479822041275856


In this example, the 5 can be represented as both rows and columns. This is very confusing. 
We will change to using a explicit notation for both dimensions:

In [5]:
a = np.random.randn(5,1)
print(a)

[[6.66419474e-01]
 [5.92448666e-04]
 [6.83277210e-01]
 [3.65093056e-01]
 [8.34188528e-01]]


In [6]:
print(a.T)

[[6.66419474e-01 5.92448666e-04 6.83277210e-01 3.65093056e-01
  8.34188528e-01]]


Avoid using rank 1 arrays.
Use the following inexpansive conde to garantee that the matrix is of the dimensions you want:

In [10]:
assert(a.shape==(5,1))

In [13]:
np.array([[[1],[2]],[[3],[4]]]).shape

(2, 2, 1)

In [14]:
a = np.random.randn(4,3)
b = np.random.randn(1,3)
a*b

array([[-0.32385776,  2.58816376, -0.20695959],
       [-0.86823762,  0.55967266, -0.71846216],
       [-0.67028886, -0.42566795, -0.71003757],
       [ 1.58625137, -3.18440525, -1.35626433]])

In [16]:
np.array([[2,1],[1,3]])*np.array([[2,1],[1,3]])

array([[4, 1],
       [1, 9]])